// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ekiden/grpc/enclaverpc.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallEnclaveRequest struct {
	// Raw request payload that will be passed to the enclave.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Endpoint identifier for cases where a single node supports multiple endpoints.
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallEnclaveRequest) Reset()         { *m = CallEnclaveRequest{} }
func (m *CallEnclaveRequest) String() string { return proto.CompactTextString(m) }
func (*CallEnclaveRequest) ProtoMessage()    {}
func (*CallEnclaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0174f08b320c04b, []int{0}
}

func (m *CallEnclaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallEnclaveRequest.Unmarshal(m, b)
}
func (m *CallEnclaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallEnclaveRequest.Marshal(b, m, deterministic)
}
func (m *CallEnclaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallEnclaveRequest.Merge(m, src)
}
func (m *CallEnclaveRequest) XXX_Size() int {
	return xxx_messageInfo_CallEnclaveRequest.Size(m)
}
func (m *CallEnclaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallEnclaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallEnclaveRequest proto.InternalMessageInfo

func (m *CallEnclaveRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CallEnclaveRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type CallEnclaveResponse struct {
	// Raw response payload from enclave.
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallEnclaveResponse) Reset()         { *m = CallEnclaveResponse{} }
func (m *CallEnclaveResponse) String() string { return proto.CompactTextString(m) }
func (*CallEnclaveResponse) ProtoMessage()    {}
func (*CallEnclaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0174f08b320c04b, []int{1}
}

func (m *CallEnclaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallEnclaveResponse.Unmarshal(m, b)
}
func (m *CallEnclaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallEnclaveResponse.Marshal(b, m, deterministic)
}
func (m *CallEnclaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallEnclaveResponse.Merge(m, src)
}
func (m *CallEnclaveResponse) XXX_Size() int {
	return xxx_messageInfo_CallEnclaveResponse.Size(m)
}
func (m *CallEnclaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallEnclaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallEnclaveResponse proto.InternalMessageInfo

func (m *CallEnclaveResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*CallEnclaveRequest)(nil), "grpc.CallEnclaveRequest")
	proto.RegisterType((*CallEnclaveResponse)(nil), "grpc.CallEnclaveResponse")
}

func init() { proto.RegisterFile("ekiden/grpc/enclaverpc.proto", fileDescriptor_b0174f08b320c04b) }

var fileDescriptor_b0174f08b320c04b = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xcd, 0xce, 0x4c,
	0x49, 0xcd, 0xd3, 0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x4f, 0xcd, 0x4b, 0xce, 0x49, 0x2c, 0x4b, 0x2d,
	0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x09, 0x2b, 0x79, 0x71, 0x09,
	0x39, 0x27, 0xe6, 0xe4, 0xb8, 0x42, 0x64, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24,
	0xb8, 0xd8, 0x0b, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82,
	0x60, 0x5c, 0x21, 0x29, 0x2e, 0x8e, 0xd4, 0xbc, 0x94, 0x82, 0xfc, 0xcc, 0xbc, 0x12, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x49, 0x9f, 0x4b, 0x18, 0xc5, 0xac, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0xdc, 0x86, 0x19, 0x05, 0x71, 0x71, 0xc1, 0x14, 0x17, 0x24, 0x0b, 0xb9, 0x70,
	0x71, 0x23, 0x69, 0x17, 0x92, 0xd0, 0x03, 0x39, 0x50, 0x0f, 0xd3, 0x75, 0x52, 0x92, 0x58, 0x64,
	0x20, 0x76, 0x29, 0x31, 0x38, 0x19, 0x44, 0xe9, 0xa5, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25,
	0xe7, 0xe7, 0xea, 0xe7, 0x27, 0x16, 0x67, 0x16, 0xe7, 0x24, 0x26, 0x15, 0x43, 0x58, 0xba, 0xe9,
	0x89, 0x25, 0xa9, 0xe5, 0x89, 0x95, 0xfa, 0x48, 0x21, 0x93, 0xc4, 0x06, 0x0e, 0x0f, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x10, 0xd4, 0x53, 0x2f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EnclaveRpcClient is the client API for EnclaveRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnclaveRpcClient interface {
	// RPC interface.
	CallEnclave(ctx context.Context, in *CallEnclaveRequest, opts ...grpc.CallOption) (*CallEnclaveResponse, error)
}

type enclaveRpcClient struct {
	cc *grpc.ClientConn
}

func NewEnclaveRpcClient(cc *grpc.ClientConn) EnclaveRpcClient {
	return &enclaveRpcClient{cc}
}

func (c *enclaveRpcClient) CallEnclave(ctx context.Context, in *CallEnclaveRequest, opts ...grpc.CallOption) (*CallEnclaveResponse, error) {
	out := new(CallEnclaveResponse)
	err := c.cc.Invoke(ctx, "/grpc.EnclaveRpc/CallEnclave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnclaveRpcServer is the server API for EnclaveRpc service.
type EnclaveRpcServer interface {
	// RPC interface.
	CallEnclave(context.Context, *CallEnclaveRequest) (*CallEnclaveResponse, error)
}

// UnimplementedEnclaveRpcServer can be embedded to have forward compatible implementations.
type UnimplementedEnclaveRpcServer struct {
}

func (*UnimplementedEnclaveRpcServer) CallEnclave(ctx context.Context, req *CallEnclaveRequest) (*CallEnclaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallEnclave not implemented")
}

func RegisterEnclaveRpcServer(s *grpc.Server, srv EnclaveRpcServer) {
	s.RegisterService(&_EnclaveRpc_serviceDesc, srv)
}

func _EnclaveRpc_CallEnclave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallEnclaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveRpcServer).CallEnclave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.EnclaveRpc/CallEnclave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveRpcServer).CallEnclave(ctx, req.(*CallEnclaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EnclaveRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.EnclaveRpc",
	HandlerType: (*EnclaveRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallEnclave",
			Handler:    _EnclaveRpc_CallEnclave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ekiden/grpc/enclaverpc.proto",
}
