package event

// AsyncResponse is the response returned by APIs that are asynchronous
// that return an ID that can be used by the user to receive and identify
// a response to the request when it is ready
type AsyncResponse struct {
	// ID to identify an asynchronous response. It uniquely identifies the
	// event and orders it in the sequence of events expected by the user
	ID int64 `json:"id"`
}

// UnsubscribeRequest is used by the user to destroy a subscription to specific
// topics on the gateway.
type UnsubscribeRequest struct {
	// ID of the subscription to be destroyed
	ID string `json:"id"`
}

// UnsubscribeResponse is used by the user to destroy a subscription to specific
// topics on the gateway.
type UnsubscribeResponse struct {
	// ID of the subscription that has been destroyed
	ID string `json:"id"`
}

// SubscribeRequest is used by the user to create a subscription to specific
// topics on the gateway.
type SubscribeRequest struct {
	// Events is the the list of event types the subscription intends
	// to be created for
	Events []string `json:"events"`

	// Filter is a url encoded list of query parameters that specifiy
	// filters to be applied to the subscribed topic
	Filter string `json:"filter"`
}

// SubscribeResponse returns an AsyncResponse which contains the ID
// that can be used to poll for notifications on the subscription
type SubscribeResponse AsyncResponse

// EventPollRequest is a request that allows the user to
// poll for events either from asynchronous requests or from
// subscriptions
type EventPollRequest struct {
	// Offset at which events need to be provided. Events are all ordered
	// with sequence numbers and it is up to the client to specifiy which
	// events it wants to receive from an offset in the sequence
	Offset int `json:"offset"`

	// Count for the number of items the client would prefer to receive
	// at most from a single response
	Count int `json:"count"`

	// DiscardPrevious allows the client to define whether the server should
	// discard all the events that have a sequence number lower than the offer
	DiscardPrevious bool `json:"discardPrevious"`
}

// EventPollResponse is the list of events that are returned for
// a subscription or a group of asynchronous requests
type EventPollResponse struct {
	// Events is the list of events that the server has starting from
	// the provided Offset
	Events []Event `json:"events"`

	// Offset is the current offset at which the provided list of events
	// start
	Offset int `json:"offset"`
}

// Event is the interface that all events that can be returned from an
// EventPollingResponse need to return
type Event interface {
	// ID to identifiy an asynchronous response. It uniquely identifies the
	// event and orders it in the sequence of events expected by the user
	ID() int64
}

// DataEvent is that event that can be polled by the user to poll
// for service logs for example, which they are a blob of data that the
// client knows how to manipulate
type DataEvent struct {
	// ID to identify the event itself withint the sequence of events.
	ID int64 `json:"id"`

	// Data is the blob of data related to this event
	Data string `json:"data"`
}

// ServiceExecutionEvent is the event that can be polled by the user
// as a result to a ServiceExecutionRequest
type ServiceExecutionEvent struct {
	// ID to identify an asynchronous response. It uniquely identifies the
	// event and orders it in the sequence of events expected by the user
	ID int64 `json:"id"`

	// Address is the unique address that identifies the service,
	// is generated when a service is deployed and it can be used
	// for service execution
	Address string `json:"address"`

	// Output generated by the service at the end of its execution
	Output string `json:"output"`
}

// ServiceDeployEvent is the event that can be polled by the user
// as a result to a ServiceExecutionRequest
type ServiceDeployEvent struct {
	// ID to identifiy an asynchronous response. It uniquely identifies the
	// event and orders it in the sequence of events expected by the user
	ID int64 `json:"id"`

	// Address is the unique address that identifies the service,
	// is generated when a service is deployed and it can be used
	// for service execution
	Address string `json:"address"`
}
